In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
df = pd.read_csv(r"C:\Users\madha\Downloads\Day_18_Tours_and_Travels.csv")
display(df.info())
display(df.head())
df['Customer_Age'].fillna(df['Customer_Age'].median(), inplace=True)
df['Rating'].fillna(df['Rating'].median(), inplace=True)
df['Review_Text'].fillna("No Review", inplace=True)
df.drop_duplicates(subset=['Review_Text', 'Customer_Age', 'Rating'], keep='first', inplace=True)
df['Rating'] = df['Rating'].clip(1, 5)
df['Tour_Package'] = df['Tour_Package'].str.title()
plt.figure(figsize=(8, 6))
sns.boxplot(x=df['Package_Price'])
plt.show()
df['Package_Price'] = df['Package_Price'].clip(lower=df['Package_Price'].quantile(0.05), 
                                               upper=df['Package_Price'].quantile(0.95))
encoder = LabelEncoder()
df['Tour_Package'] = encoder.fit_transform(df['Tour_Package'])
scaler = MinMaxScaler()
df[['Customer_Age', 'Package_Price']] = scaler.fit_transform(df[['Customer_Age', 'Package_Price']])
df.to_csv("cleaned_travel_reviews.csv", index=False)
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Booking_ID     505 non-null    int64
 1   Destination    478 non-null    object
 2   Package_Price  485 non-null    float64
 3   Customer_Age   490 non-null    float64
 4   Rating         480 non-null    float64
 5   Review_Text    485 non-null    object
 6   Travel_Date    495 non-null    object
dtypes: float64(3), int64(1), object(3)
memory usage: 27.7+ KB

None

,Booking_ID,Destination,Package_Price,Customer_Age,Rating,Review_Text,Travel_Date
0,1,London,1094.0,21.0,NaN,Amazing experience!,2023-01-01
1,2,Paris,640.0,20.0,NaN,Loved the trip!,2023-01-02
2,3,Singapore,3393.0,42.0,3.0,Could be better,2023-01-03
3,4,London,3555.0,40.0,4.0,Amazing experience!,2023-01-04
4,5,Dubai,2130.0,44.0,2.0,Highly recommended,2023-01-05

C:\Users\madha\AppData\Local\Temp\ipykernel_3384\1782897682.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_Age'].fillna(df['Customer_Age'].median(), inplace=True)
C:\Users\madha\AppData\Local\Temp\ipykernel_3384\1782897682.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Rating'].fillna(df['Rating'].median(), inplace=True)
C:\Users\madha\AppData\Local\Temp\ipykernel_3384\1782897682.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Review_Text'].fillna("No Review", inplace=True)

KeyError: 'Tour_Package'